name: C++ CI

on:
    push:
    pull_request:

jobs:
    linux:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                build_type: [Debug, Release]
                compiler: [g++, clang++]
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Configure CMake
              run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}

            - name: Build
              run: cmake --build build

            - name: Run tests
              run: ctest --test-dir build --output-on-failure
    
    windows:
        runs-on: windows-latest

        strategy:
            matrix:
                build_type: [Debug, Release]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Configure CMake
              run: cmake -S . -B build 

            - name: Build
              run: cmake --build build --config ${{ matrix.build_type }}
            
            - name: Run tests
              run: ctest --test-dir build -C ${{ matrix.build_type }} --output-on-failure

    